version: "3.9"

services:
    web:
        build: .
        image: refresh-token-api:1.0.0
        container_name: api-refresh-token
        ports: 
        - "8080:80" 
        networks:
            - backend-network
        depends_on:
            - db
            - redis
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: sql-server-express
        environment:
            SA_PASSWORD: "Test@123"
            ACCEPT_EULA: "Y"
            MSSQL_PID : "Express"
        ports : 
            - 51433:1433
        networks:
            - backend-network
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend-network

networks:
    backend-network:
        driver: bridge
         